name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, intl
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Run static analysis (phpstan)
        run: composer run stan || true
      - name: Run tests
        run: composer test
